### ISSUE TITLE
Performance: Do we need to load the section from the database?

### ISSUE THREAD

**Issue by mudrd8mz** [bdecentgmbh/moodle-availability_sectioncompleted#3]
Do we really need to touch the DB here? 

https://github.com/bdecentgmbh/moodle-availability_sectioncompleted/blob/fc5c84fdc2d3af639f61b3f7a7dc19a60e333dc2/classes/condition.php#L124

What is the purpose? Every extra DB query contributes to DB load and has cumulative impact on performance.

Also, at the line below it, it does not look right to check `if (isset($section))` - the `get_record()` would return false if the section did not exist. But it would still be set. Fixing this will also eliminate the need to use the at-sign operator in `[@$section->section]`.

**Comment by stefanscholz** [comment]
We removed the extra DB query in version 1.03 (will be released shortly).
