### ISSUE TITLE
Feature request: Restriction by completion of the previous section

### ISSUE THREAD

**Issue by brunohcury** [bdecentgmbh/moodle-availability_sectioncompleted#4]
Hi,
Very good your plugin, it really meets the needs.
You know if I can set "restrict completing the previous section". Because if we had this option, the mobility of the sections would certainly be more dynamic.
Just by dragging the section to the correct order, the plugin would already understand that the conclusion now becomes the previous section, avoiding changing the plugin settings again and manually to the correct section.
Thank you very much

**Comment by stefanscholz** [comment]
Hi! Glad you like the plugin and find it useful. And thanks for the feature request! It’s certainly a great idea and I’ll put it on the roadmap for the next version. I’ll keep you posted! Best Stefan

**Comment by stefanscholz** [comment]
New feature in version 1.03.
