### ISSUE TITLE
condiction is not triggering

### ISSUE THREAD

**Issue by danweb80** [bdecentgmbh/moodle-availability_sectioncompleted#7]
Hello,

I found this bug: The condiction is not triggering. All modules are concluded but the completion is not recognized. This happened in yhis specifica section... in others are ok.
Look at the print:
![image](https://github.com/bdecentgmbh/moodle-availability_sectioncompleted/assets/135277031/94ca0e5a-a091-4ffb-844a-4d996c79429d)

**Comment by stefanscholz** [comment]
We have tried to reproduce this issue on our test sites and were not able to find any issues. Kindly reopen this issue and provide step-by-step instructions to reproduce this issue (in english please). Many thanks!
