### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Not implemented (do not call unless is_applied_to_user_lists is true)

### ISSUE THREAD

**Issue by Redcryp7o** [bdecentgmbh/moodle-availability_sectioncompleted#8]
I faced this error when i click on the restricted list that i restrict for students that they can access it until previous work is not completed. i am currently using moodle 4.2+.

**Comment by stefanscholz** [comment]
Hi @RedCryp7o ,

could you please check if the latest version of the plugin (released 2 weeks ago) solves your issue? I cannot reproduce it with the latest version. Please re-open this issue if you still have the issue and provide more details on how to reproduce the issue.

Many thanks!
Stefan

**Comment by Redcryp7o** [comment]
I will check the latest version. Thanks for reply.
